### ISSUE TITLE
请问您的代码中是否需要将输入数据全部归一化到[-0.5, 0.5]的范围呢

### ISSUE THREAD

**Issue by Ritatanz** [summitgao/HC_ADGAN#1]

**Comment by summitgao** [comment]
非常抱歉，今天发现 github  打不开了。。。明天我再看看




At 2021-12-22 17:18:10, "Ritatanz" ***@***.***> wrote:

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by summitgao** [comment]
非常抱歉，今天才看到这个问题。。。如果还有疑问，欢迎邮件联系  gaofeng@ouc.edu.cn，谢谢！
